grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.monitoring.svc
      isDefault: false
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc:3100
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
        serviceMap:
          datasourceUid: Prometheus

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi

alertmanager:
  alertmanagerSpec:
    retention: 120h

kubeEtcd:
  enabled: false
