tempo:
  reportingEnabled: false
  metricsGenerator:
    enabled: true

serviceMonitor:
  enabled: true

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

